server:
  address: ":7777"
  openapiPath: "/api.json"
  logStdout: true
  errorStack: true
  errorLogEnabled: true
logger:
  path: ".logs"
  level: "all"
  stdout: true
database:
  default:
    host: "localhost"
    port: "5432"
    user: "xiaoservice"
    pass: "xiaoservice"
    name: "xiaoservice"
    type: "pgsql"
redis:
  default:
    address: "localhost:6379"
    db:      1