// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package mail

import (
	"bamboo-service/api/mail"
)

type ControllerV1 struct{}

func NewV1() mail.IMailV1 {
	return &ControllerV1{}
}
