// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"bamboo-service/internal/dao/internal"
)

// fyUserDao is the data access object for the table fy_user.
// You can define custom methods on it to extend its functionality as needed.
type fyUserDao struct {
	*internal.FyUserDao
}

var (
	// FyUser is a globally accessible object for table fy_user operations.
	FyUser = fyUserDao{internal.NewFyUserDao()}
)

// Add your custom methods and functionality below.
