// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"bamboo-service/internal/dao/internal"
)

// permissionDao is the data access object for the table fy_permission.
// You can define custom methods on it to extend its functionality as needed.
type permissionDao struct {
	*internal.PermissionDao
}

var (
	// Permission is a globally accessible object for table fy_permission operations.
	Permission = permissionDao{internal.NewPermissionDao()}
)

// Add your custom methods and functionality below.
