// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"bamboo-service/internal/dao/internal"
)

// proxyGroupDao is the data access object for the table fy_proxy_group.
// You can define custom methods on it to extend its functionality as needed.
type proxyGroupDao struct {
	*internal.ProxyGroupDao
}

var (
	// ProxyGroup is a globally accessible object for table fy_proxy_group operations.
	ProxyGroup = proxyGroupDao{internal.NewProxyGroupDao()}
)

// Add your custom methods and functionality below.
