// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"bamboo-service/internal/dao/internal"
)

// proxySubscriptionDao is the data access object for the table fy_proxy_subscription.
// You can define custom methods on it to extend its functionality as needed.
type proxySubscriptionDao struct {
	*internal.ProxySubscriptionDao
}

var (
	// ProxySubscription is a globally accessible object for table fy_proxy_subscription operations.
	ProxySubscription = proxySubscriptionDao{internal.NewProxySubscriptionDao()}
)

// Add your custom methods and functionality below.
