// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"bamboo-service/internal/dao/internal"
)

// userDao is the data access object for the table fy_user.
// You can define custom methods on it to extend its functionality as needed.
type userDao struct {
	*internal.UserDao
}

var (
	// User is a globally accessible object for table fy_user operations.
	User = userDao{internal.NewUserDao()}
)

// Add your custom methods and functionality below.
